import './globals.css';
import { Inter } from 'next/font/google';
import GTagLoader from './components/GTagLoader';
import Analytics from './components/Analytics';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <GTagLoader />
      <Analytics />
      <body>{children}</body>
    </html>
  );
}
